In [1]:
%pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126
     ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
     ---------------------------------------- 536.2/536.2 kB 2.5 MB/s  0:00:00
   ---------------------------------------- 0.0/2.6 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 GB 2.4 MB/s eta 0:17:52
   ---------------------------------------- 0.0/2.6 GB 3.0 MB/s eta 0:14:32
   ---------------------------------------- 0.0/2.6 GB 3.4 MB/s eta 0:12:42
   ---------------------------------------- 0.0/2.6 GB 3.2 MB/s eta 0:13:26
   ---------------------------------------- 0.0/2.6 GB 3.6 MB/s eta 0:11:58
   ---------------------------------------- 0.0/2.6 GB 3.9 MB/s eta 0:11:00
   ---------------------------------------- 0.0/2.6 GB 4.2 MB/s eta 0:10:26
   ---------------------------------------- 0.0/2.6 GB 4.4 MB/s eta 0:09:56
   ---------------------------------------- 0.0/2.6 GB 4.6 MB/s eta 0:09:31
   ---------------------------------

In [2]:
import torch

In [3]:
torch.cuda.is_available()

False

In [4]:
torch.__version__

'2.9.0+cu126'

In [5]:
import numpy as np

In [6]:
data = [[1, 2],
        [3,4]]

In [7]:
x = torch.tensor(data)
x

tensor([[1, 2],
        [3, 4]])

In [8]:
x_np = np.array(x)

x_tensor = torch.from_numpy(x_np)
x_tensor

C:\Users\user\AppData\Local\Temp\ipykernel_4820\2376230143.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  x_np = np.array(x)


tensor([[1, 2],
        [3, 4]])

In [9]:
x[0]

tensor([1, 2])

In [10]:
x[0][0]

tensor(1)

In [11]:
x.size()

torch.Size([2, 2])

In [12]:
x[0].size()

torch.Size([2])

In [13]:
x.size()[0]

2

In [14]:
y = torch.tensor(np.array([[5, 6], [7, 8]]))

In [15]:
x + y

tensor([[ 6,  8],
        [10, 12]])

In [16]:
torch.add(x, y)

tensor([[ 6,  8],
        [10, 12]])

In [17]:
x.add(y)

tensor([[ 6,  8],
        [10, 12]])

In [18]:
x

tensor([[1, 2],
        [3, 4]])

In [19]:
y

tensor([[5, 6],
        [7, 8]])

In [21]:
# inplace=True
y.add_(x)
# 수정한 값을 원본에 바로 적용한다는 설정 inplace=True

tensor([[ 7, 10],
        [13, 16]])

In [22]:
x_reshape01 = x.view(4)
x_reshape01

tensor([1, 2, 3, 4])

In [23]:
x_reshape02 = x.view(-1)
x_reshape02

tensor([1, 2, 3, 4])

In [24]:
x_to_np = x.numpy()
x_to_np

array([[1, 2],
       [3, 4]])

In [25]:
type(x_to_np)

numpy.ndarray

In [26]:
type(x)

torch.Tensor