In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np
import pandas as pd

In [3]:
random_num = np.random.randint(1, 101, [3, 3])
random_num
# 행렬

array([[19, 70,  8],
       [25, 11, 58],
       [94, 57, 15]], dtype=int32)

In [6]:
df_num = pd.DataFrame(random_num)
df_num
# 데이터프레임으로 변환해줌

0   1   2
0  19  70   8
1  25  11  58
2  94  57  15

In [7]:
df_num = pd.DataFrame(random_num, index=["row1", "row2", "row3"])
df_num

0   1   2
row1  19  70   8
row2  25  11  58
row3  94  57  15

In [8]:
df_num = pd.DataFrame(random_num,
                      index=["row1", "row2", "row3"],
                      columns=["col1", "col2", "col3"])
df_num

col1  col2  col3
row1    19    70     8
row2    25    11    58
row3    94    57    15

In [9]:
print(type(random_num))

<class 'numpy.ndarray'>


In [10]:
print(type(df_num))

<class 'pandas.core.frame.DataFrame'>


In [11]:
# 출력 형식 차이
# 파이참 미적 감각 무시 ㅋ
print(random_num)

[[19 70  8]
 [25 11 58]
 [94 57 15]]


In [12]:
print(df_num)

      col1  col2  col3
row1    19    70     8
row2    25    11    58
row3    94    57    15


In [15]:
books = {
    "title" : ["개미", "고구려", "드래곤라자", "퇴마록"],
    "writer": ["베르나르 베르베르", "김진명", "이영도", "이우혁"],
    "publisher": ["열린책들", "이타북스", "황금가지", "들녘"],
    "1st-edition": ["2013-05-30", "2011-02-28", "1998-05-30", "1994-01-01"],
    "price" : [15000, 15000, 6300, 8550]
}

In [16]:
books

{'title': ['개미', '고구려', '드래곤라자', '퇴마록'],
 'writer': ['베르나르 베르베르', '김진명', '이영도', '이우혁'],
 'publisher': ['열린책들', '이타북스', '황금가지', '들녘'],
 '1st-edition': ['2013-05-30', '2011-02-28', '1998-05-30', '1994-01-01'],
 'price': [15000, 15000, 6300, 8550]}

In [17]:
df_books = pd.DataFrame(books)
df_books

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550

In [18]:
print(df_books)

   title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550


In [26]:
df_books.index
df_books.columns
df_books.shape
df_books.size
print(df_books.dtypes)
type(df_books.dtypes)
print(df_books.count())

RangeIndex(start=0, stop=4, step=1)

Index(['title', 'writer', 'publisher', '1st-edition', 'price'], dtype='object')

(4, 5)

20

title          object
writer         object
publisher      object
1st-edition    object
price           int64
dtype: object


pandas.core.series.Series

title          4
writer         4
publisher      4
1st-edition    4
price          4
dtype: int64


In [28]:
df_books.info
df_books.info()

<bound method DataFrame.info of    title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   title        4 non-null      object
 1   writer       4 non-null      object
 2   publisher    4 non-null      object
 3   1st-edition  4 non-null      object
 4   price        4 non-null      int64 
dtypes: int64(1), object(4)
memory usage: 292.0+ bytes


In [30]:
df_books["title"][0]

'개미'

In [31]:
type(df_books["title"])

pandas.core.series.Series

In [32]:
df_books["price"].max()

np.int64(15000)

In [33]:
df_books["price"].min()

np.int64(6300)

In [35]:
df_books.sort_values(by="price")

title     writer publisher 1st-edition  price
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550
1    고구려        김진명      이타북스  2011-02-28  15000
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000

In [37]:
df_books.sort_values(by="price", ascending=False)
# 내림차순 설정

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
3    퇴마록        이우혁        들녘  1994-01-01   8550
2  드래곤라자        이영도      황금가지  1998-05-30   6300

In [38]:
df_books.sort_values(["price", "1st-edition"], ascending=False)

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
3    퇴마록        이우혁        들녘  1994-01-01   8550
2  드래곤라자        이영도      황금가지  1998-05-30   6300

In [40]:
df_books.sort_values(["price", "1st-edition"], ascending=[False, True])

title     writer publisher 1st-edition  price
1    고구려        김진명      이타북스  2011-02-28  15000
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
3    퇴마록        이우혁        들녘  1994-01-01   8550
2  드래곤라자        이영도      황금가지  1998-05-30   6300

In [41]:
df_books.sort_index()

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550

In [42]:
df_books.sort_index(axis=1)

1st-edition  price publisher  title     writer
0  2013-05-30  15000      열린책들     개미  베르나르 베르베르
1  2011-02-28  15000      이타북스    고구려        김진명
2  1998-05-30   6300      황금가지  드래곤라자        이영도
3  1994-01-01   8550        들녘    퇴마록        이우혁

In [43]:
df_books.sort_index(axis="columns")

1st-edition  price publisher  title     writer
0  2013-05-30  15000      열린책들     개미  베르나르 베르베르
1  2011-02-28  15000      이타북스    고구려        김진명
2  1998-05-30   6300      황금가지  드래곤라자        이영도
3  1994-01-01   8550        들녘    퇴마록        이우혁

In [45]:
df_title = df_books.set_index("title")

In [46]:
df_title

writer publisher 1st-edition  price
title                                        
개미     베르나르 베르베르      열린책들  2013-05-30  15000
고구려          김진명      이타북스  2011-02-28  15000
드래곤라자        이영도      황금가지  1998-05-30   6300
퇴마록          이우혁        들녘  1994-01-01   8550

In [47]:
df_title.index

Index(['개미', '고구려', '드래곤라자', '퇴마록'], dtype='object', name='title')

In [48]:
df_title.values

array([['베르나르 베르베르', '열린책들', '2013-05-30', 15000],
       ['김진명', '이타북스', '2011-02-28', 15000],
       ['이영도', '황금가지', '1998-05-30', 6300],
       ['이우혁', '들녘', '1994-01-01', 8550]], dtype=object)

In [50]:
df_title["price"]

title
개미       15000
고구려      15000
드래곤라자     6300
퇴마록       8550
Name: price, dtype: int64

In [51]:
type(df_title["price"])
# 인덱스가 title이 된 시리즈 타입 맞는지 확인

pandas.core.series.Series

In [52]:
df_title.nlargest(3, columns="price")

writer publisher 1st-edition  price
title                                        
개미     베르나르 베르베르      열린책들  2013-05-30  15000
고구려          김진명      이타북스  2011-02-28  15000
퇴마록          이우혁        들녘  1994-01-01   8550

In [53]:
df_title.nsmallest(2, columns="price")

writer publisher 1st-edition  price
title                                    
드래곤라자    이영도      황금가지  1998-05-30   6300
퇴마록      이우혁        들녘  1994-01-01   8550

In [54]:
df_title.sum()

writer                               베르나르 베르베르김진명이영도이우혁
publisher                                열린책들이타북스황금가지들녘
1st-edition    2013-05-302011-02-281998-05-301994-01-01
price                                             44850
dtype: object

In [55]:
df_title

writer publisher 1st-edition  price
title                                        
개미     베르나르 베르베르      열린책들  2013-05-30  15000
고구려          김진명      이타북스  2011-02-28  15000
드래곤라자        이영도      황금가지  1998-05-30   6300
퇴마록          이우혁        들녘  1994-01-01   8550

In [56]:
# 컬럼별로 값을 더함. == 시리즈별로 값을 더함
df_title.sum()

writer                               베르나르 베르베르김진명이영도이우혁
publisher                                열린책들이타북스황금가지들녘
1st-edition    2013-05-302011-02-281998-05-301994-01-01
price                                             44850
dtype: object

In [57]:
df_title["price"].sum()

np.int64(44850)

In [58]:
df_title.sum(numeric_only=True)

price    44850
dtype: int64

In [60]:
df_title.sum(numeric_only=False) # 기본값 false

writer                               베르나르 베르베르김진명이영도이우혁
publisher                                열린책들이타북스황금가지들녘
1st-edition    2013-05-302011-02-281998-05-301994-01-01
price                                             44850
dtype: object

In [64]:
df_title.mean(numeric_only=True)

price    11212.5
dtype: float64

In [65]:
df_title.median(numeric_only=True)

price    11775.0
dtype: float64

In [66]:
df_title.std(numeric_only=True)

price    4468.850523
dtype: float64

In [67]:
df_title.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 개미 to 퇴마록
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   writer       4 non-null      object
 1   publisher    4 non-null      object
 2   1st-edition  4 non-null      object
 3   price        4 non-null      int64 
dtypes: int64(1), object(3)
memory usage: 332.0+ bytes


In [68]:
df_title.info

<bound method DataFrame.info of           writer publisher 1st-edition  price
title                                        
개미     베르나르 베르베르      열린책들  2013-05-30  15000
고구려          김진명      이타북스  2011-02-28  15000
드래곤라자        이영도      황금가지  1998-05-30   6300
퇴마록          이우혁        들녘  1994-01-01   8550>

In [69]:
df_title.select_dtypes("object")
# object 타입으로 되어있는애들만 보여줘

writer publisher 1st-edition
title                                 
개미     베르나르 베르베르      열린책들  2013-05-30
고구려          김진명      이타북스  2011-02-28
드래곤라자        이영도      황금가지  1998-05-30
퇴마록          이우혁        들녘  1994-01-01

In [71]:
df_title.select_dtypes("int")

price
title       
개미     15000
고구려    15000
드래곤라자   6300
퇴마록     8550

In [72]:
df_title["1st-edition"] = pd.to_datetime(df_title["1st-edition"])

In [73]:
df_title.select_dtypes("object")

writer publisher
title                     
개미     베르나르 베르베르      열린책들
고구려          김진명      이타북스
드래곤라자        이영도      황금가지
퇴마록          이우혁        들녘

In [74]:
df_title.select_dtypes(include="object")

writer publisher
title                     
개미     베르나르 베르베르      열린책들
고구려          김진명      이타북스
드래곤라자        이영도      황금가지
퇴마록          이우혁        들녘

In [75]:
df_title.select_dtypes(exclude="object")

1st-edition  price
title                   
개미     2013-05-30  15000
고구려    2011-02-28  15000
드래곤라자  1998-05-30   6300
퇴마록    1994-01-01   8550

In [76]:
df_title["price"]

title
개미       15000
고구려      15000
드래곤라자     6300
퇴마록       8550
Name: price, dtype: int64

In [77]:
df_title["publisher"]

title
개미       열린책들
고구려      이타북스
드래곤라자    황금가지
퇴마록        들녘
Name: publisher, dtype: object

In [78]:
# 두개를 조회해서 보고싶을때
df_title[["price", "publisher"]]

price publisher
title                 
개미     15000      열린책들
고구려    15000      이타북스
드래곤라자   6300      황금가지
퇴마록     8550        들녘

In [80]:
# 잘못된 사례
df_title["price", "publisher"]
# KeyError: ('price', 'publisher')

KeyError: ('price', 'publisher')

In [81]:
# 알맞은 사례. 대괄호 하나 더 작성해줌
df_title[["price", "publisher"]]

price publisher
title                 
개미     15000      열린책들
고구려    15000      이타북스
드래곤라자   6300      황금가지
퇴마록     8550        들녘

In [82]:
print(df_title.loc["드래곤라자"])

writer                         이영도
publisher                     황금가지
1st-edition    1998-05-30 00:00:00
price                         6300
Name: 드래곤라자, dtype: object


In [84]:
print(df_title.iloc[2])

writer                         이영도
publisher                     황금가지
1st-edition    1998-05-30 00:00:00
price                         6300
Name: 드래곤라자, dtype: object


In [85]:
df_title.loc[["고구려", "드래곤라자"]]

writer publisher 1st-edition  price
title                                    
고구려      김진명      이타북스  2011-02-28  15000
드래곤라자    이영도      황금가지  1998-05-30   6300

In [86]:
df_title.iloc[[1, 2]]

writer publisher 1st-edition  price
title                                    
고구려      김진명      이타북스  2011-02-28  15000
드래곤라자    이영도      황금가지  1998-05-30   6300

In [87]:
df_title.iloc[2:4]

writer publisher 1st-edition  price
title                                    
드래곤라자    이영도      황금가지  1998-05-30   6300
퇴마록      이우혁        들녘  1994-01-01   8550