# MarkDown

**명령어**

enter : edit mode

esc : command mode

[edit mode] ctrl + enter : 실행

[edit mode] shift + enter : 실행 및 다음 cell 선택

[edit mode] alt + enter : 실행 및 새로운 cell 생성

[command mode] + a : 현재 cell 위에 cell 추가

[command mode] + b : 현재 cell 아래에 cell 추가

[command mode] + y : 현재 cell을 code cell로 변경

[command mode] + m : 현재 cell을 markdown cell로 변경

! : shell 명령어 사용

% : magic function 사용 (!와 거의 동일하지만, python 명령어임)

In [213]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [243]:
!dir

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: 506E-7012

 C:\workspaces\multi01_python\13_numpy ���͸�

2025-09-26  ���� 04:43    <DIR>          .
2025-09-26  ���� 04:43    <DIR>          ..
2025-09-26  ���� 10:06    <DIR>          .ipynb_checkpoints
2025-09-26  ���� 04:06            52,234 card_ex.ipynb
2025-09-26  ���� 04:43            33,682 np01.ipynb
2025-09-26  ���� 02:40            24,992 np02.ipynb
2025-09-26  ���� 03:20            14,154 np03.ipynb
               4�� ����             125,062 ����Ʈ
               3�� ���͸�  173,123,018,752 ����Ʈ ����


In [214]:
!pip install numpy

In [215]:
import numpy as np

In [216]:
np.__version__

'2.2.6'

In [217]:
# 자동완성 : tab
# docstring (설명) : shift + tab
np.array

<function numpy.array>

In [218]:
arr01 = np.array([1, 2, 3, 4, 5])

In [219]:
arr01

array([1, 2, 3, 4, 5])

In [220]:
type(arr01)
# ndarray : n dimensional array

numpy.ndarray

In [221]:
arr02 = np.array([
    [1.1, 2.2, 3.3],
    [4, 5, 6]
])

In [222]:
arr02

array([[1.1, 2.2, 3.3],
       [4. , 5. , 6. ]])

In [223]:
list_dim3 = [
    [["1"], ["2"], ["3"]],
    [[4], [5], [6]],
    [[7], [8], [9]],
    [["10"], ["11"], ["12"]]
]

arr03 = np.array(list_dim3)
arr03

array([[['1'],
        ['2'],
        ['3']],

       [['4'],
        ['5'],
        ['6']],

       [['7'],
        ['8'],
        ['9']],

       [['10'],
        ['11'],
        ['12']]], dtype='<U21')

In [224]:
# shape : 차원 출력 (1, 2, 3, ... n차원)

# (5, ) : 1차원, 데이터 5개
print(arr01.shape)
# (2, 3) : 2차원, 2행 3열
print(arr02.shape)
# (4, 3, 1) : 3차원, 4개의 2차원 -> (3, 1) : 3행 1열
print(arr03.shape)

(5,)
(2, 3)
(4, 3, 1)


In [225]:
arr01

array([1, 2, 3, 4, 5])

In [226]:
arr02

array([[1.1, 2.2, 3.3],
       [4. , 5. , 6. ]])

In [227]:
arr03

array([[['1'],
        ['2'],
        ['3']],

       [['4'],
        ['5'],
        ['6']],

       [['7'],
        ['8'],
        ['9']],

       [['10'],
        ['11'],
        ['12']]], dtype='<U21')

In [228]:
# ndim : 차원 갯수
print(arr01.ndim)
print(arr02.ndim)
print(arr03.ndim)

1
2
3


In [229]:
# dtype : ndarray 내부의 값들이 어떤 type인지
print(arr01.dtype)
print(arr02.dtype)
print(arr03.dtype)

int64
float64
<U21


In [230]:
print(arr01.size)
print(arr02.size)
print(arr03.size)

5
6
12


In [231]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# print 없이 여러 개의 변수를 모두 출력

In [232]:
arr01.size
arr02.size
arr03.size

5

6

12

**Ipython.core.interactiveshell 에서 ast_node_interactivity 를 all로 설정해서 마지막 변수값만 출력하는 기본 설정값을 어기고 모든 변수값을 출력한것을 확인할수있음**

In [233]:
np.arange(3)

array([0, 1, 2])

In [234]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [235]:
arr04 = np.arange(0, 11, 2)
arr04
arr04.shape

array([ 0,  2,  4,  6,  8, 10])

(6,)

In [236]:
type(arr04)

numpy.ndarray

In [237]:
type(arr01)

numpy.ndarray

In [238]:
arr04.shape

(6,)

In [239]:
arr04

array([ 0,  2,  4,  6,  8, 10])

In [240]:
arr04 = arr04.reshape(2, 3)
arr04.shape
arr04

(2, 3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [241]:
arr05 = np.arange(100)
arr05

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [242]:
arr05.reshape(2, 3)
# ValueError: cannot reshape array of size 100 into shape (2,3)

ValueError: cannot reshape array of size 100 into shape (2,3)

In [152]:
# -1 : numpy가 알아서 추론
arr05 = arr05.reshape(2, -1)
arr05.shape
arr05

(2, 50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [153]:
arr05 = arr05.reshape(-1, 2)
arr05.shape
arr05

(50, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [159]:
arr06 = np.zeros(5)
arr07 = np.ones(10)
arr08 = np.empty(5)

In [162]:
arr06
arr07
arr08

array([0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34609111e-307,
       5.63234836e-322])

In [165]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [166]:
np.linspace(0, 12, num=5)

array([ 0.,  3.,  6.,  9., 12.])

In [168]:
np.linspace(0, 3, num=5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [169]:
np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [172]:
np.full((10,3), 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [173]:
# 단위행렬 : 곱셈에 대한 항등원
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [175]:
np.random.random()
np.random.random(5)
np.random.random( (2, 3) )

0.8925077303627365

array([0.3284995 , 0.84431196, 0.56654396, 0.72478776, 0.71769185])

array([[0.51216754, 0.1071704 , 0.92435569],
       [0.12013247, 0.41227078, 0.58494426]])

In [176]:
list(np.random.random(5))

[np.float64(0.5310060007355675),
 np.float64(0.37161019646108984),
 np.float64(0.8130259882720684),
 np.float64(0.16078597778272652),
 np.float64(0.336038807471728)]

In [204]:
np.random.seed(1)
np.random.randint(0, 10, (2,3))

array([[5, 8, 9],
       [5, 0, 0]], dtype=int32)

In [205]:
np.random.randn(5)
np.random.rand(2, 3)

array([-1.601721  , -1.47782957,  0.48349585,  0.18843661, -0.46468632])

array([[0.52454816, 0.44345289, 0.22957721],
       [0.53441391, 0.91396202, 0.45720481]])

In [206]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [207]:
np.arange(1, 101).dtype

dtype('int64')

In [210]:
# 정수형인데 나는 실수타입으로 변경하고싶어할때 dtype=float으로 속성을 넣어주면 됨
np.arange(1, 101, dtype=float)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])