In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1, 100, (3, 3))

In [5]:
a

array([[19, 16, 14],
       [54, 36, 23],
       [78, 22, 57]], dtype=int32)

In [6]:
b = a.copy()
b

array([[19, 16, 14],
       [54, 36, 23],
       [78, 22, 57]], dtype=int32)

In [7]:
b.sort()
b

array([[14, 16, 19],
       [23, 36, 54],
       [22, 57, 78]], dtype=int32)

In [8]:
c = a.copy()
c

array([[19, 16, 14],
       [54, 36, 23],
       [78, 22, 57]], dtype=int32)

In [9]:
c.sort(axis=0)
c

array([[19, 16, 14],
       [54, 22, 23],
       [78, 36, 57]], dtype=int32)

In [10]:
d = a.copy()
d

array([[19, 16, 14],
       [54, 36, 23],
       [78, 22, 57]], dtype=int32)

In [11]:
d.sort(axis=1)
d

array([[14, 16, 19],
       [23, 36, 54],
       [22, 57, 78]], dtype=int32)

In [12]:
e = np.arange(25).reshape(5, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
e[0]

array([0, 1, 2, 3, 4])

In [14]:
e[0][0]

np.int64(0)

In [15]:
e[0][1]

np.int64(1)

In [17]:
# fancy indexing
e[0, 0]

np.int64(0)

In [18]:
e[1:][1:]
# ==
# e[행:열][행:열]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
e[1: , 1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [20]:
e[1:-1, 1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [21]:
e[np.array([0, 1])]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
# e[[행], [열]]
e[np.array([0, 1]), np.array([0, 1])]

array([0, 6])

In [23]:
e[(0, 1, 2), (0, 1, 2)]
# (0,0), (1,1), (2,2) 를 가져와서 ndarray로 만들어서 반환해줌

array([ 0,  6, 12])

In [25]:
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
e[e%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [27]:
e[e < 5]

array([0, 1, 2, 3, 4])

In [28]:
e < 5

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [29]:
e[e<=5]

array([0, 1, 2, 3, 4, 5])