In [171]:
import seaborn as sns

In [172]:
penguins = sns.load_dataset("penguins")

naive bayes, knn(k=3), decision tree(depth=3)로 펭귄의 종을 예측하는 모델을 만들고 학습시키자

각 모델의 정확도, f1 score, precision score, recall score, roc auc score 를 출력하자

In [173]:
penguins

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [174]:
x = penguins[["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]]
y = penguins["species"]

In [175]:
x

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
3               NaN            NaN                NaN          NaN
4              36.7           19.3              193.0       3450.0
..              ...            ...                ...          ...
339             NaN            NaN                NaN          NaN
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[344 rows x 4 columns]

In [176]:
y

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...  
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

In [177]:
x.isna().sum()

bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          2
dtype: int64

In [178]:
y.isna().sum()

np.int64(0)

In [179]:
x = x.dropna()
y = y.loc[x.index]

In [180]:
x

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
4              36.7           19.3              193.0       3450.0
5              39.3           20.6              190.0       3650.0
..              ...            ...                ...          ...
338            47.2           13.7              214.0       4925.0
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[342 rows x 4 columns]

In [181]:
y

0      Adelie
1      Adelie
2      Adelie
4      Adelie
5      Adelie
        ...  
338    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 342, dtype: object

In [182]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [183]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [184]:
naive_model = GaussianNB()

In [185]:
naive_model.fit(x_train, y_train)

GaussianNB()

In [186]:
from sklearn.neighbors import KNeighborsClassifier

In [187]:
knn_model = KNeighborsClassifier(n_neighbors=3)

In [188]:
knn_model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [189]:
from sklearn.tree import DecisionTreeClassifier

In [190]:
decision_model = DecisionTreeClassifier(max_depth=3)
decision_model.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [191]:
# 각 모델의 정확도, f1 score, precision score, recall score, roc auc score 를 출력하자

In [192]:
# naive_model, knn_model, decision_model

In [193]:
naive_model.score(x_test, y_test)

0.9611650485436893

In [194]:
knn_model.score(x_test, y_test)

0.8252427184466019

In [195]:
decision_model.score(x_test, y_test)

0.9611650485436893

In [196]:
naive_predict = naive_model.predict(x_test)

In [197]:
accuracy_score(y_test, naive_predict)

0.9611650485436893

In [198]:
knn_predict = knn_model.predict(x_test)

In [199]:
accuracy_score(y_test, knn_predict)

0.8252427184466019

In [200]:
decision_predict = decision_model.predict(x_test)

In [201]:
accuracy_score(y_test, decision_predict)

0.9611650485436893

In [202]:
from sklearn.metrics import f1_score

In [203]:
f1_score(y_test, naive_predict, average=None)

array([0.95652174, 0.88235294, 1.        ])

In [204]:
f1_score(y_test, knn_predict, average=None)

array([0.8172043 , 0.53333333, 0.93975904])

In [205]:
f1_score(y_test, decision_predict, average=None)

array([0.95652174, 0.91428571, 0.98734177])

In [206]:
from sklearn.metrics import precision_score

In [208]:
precision_score(y_test, naive_predict, average=None)

array([0.93617021, 0.9375    , 1.        ])

In [209]:
precision_score(y_test, knn_predict, average=None)

array([0.79166667, 0.66666667, 0.90697674])

In [210]:
precision_score(y_test, decision_predict, average=None)

array([0.93617021, 0.94117647, 1.        ])

In [211]:
from sklearn.metrics import recall_score

In [212]:
recall_score(y_test, naive_predict, average=None)

array([0.97777778, 0.83333333, 1.        ])

In [213]:
recall_score(y_test, knn_predict, average=None)

array([0.84444444, 0.44444444, 0.975     ])

In [214]:
recall_score(y_test, decision_predict, average=None)

array([0.97777778, 0.88888889, 0.975     ])

In [215]:
from sklearn.metrics import roc_auc_score

In [219]:
naive_proba = naive_model.predict_proba(x_test)

In [221]:
roc_auc_score(y_test, naive_proba, multi_class="ovo")

np.float64(0.9921810699588477)

In [222]:
knn_proba = knn_model.predict_proba(x_test)

In [223]:
roc_auc_score(y_test, knn_proba, multi_class="ovo")

np.float64(0.870432098765432)

In [224]:
decision_proba = decision_model.predict_proba(x_test)

In [225]:
roc_auc_score(y_test, decision_proba, multi_class="ovo")

np.float64(0.9951748971193416)