In [7]:
import pandas as pd
import numpy as np

In [8]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
row_df = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)
data = np.hstack([row_df.values[::2, :], row_df.values[1::2, :2]])
target = row_df.values[1::2, 2]

In [9]:
x = pd.DataFrame(data, columns=["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT"])

y = pd.DataFrame(target, columns=["PRICE"])

LinearRegression, Ridge, Lasso, ElasticNet 학습하여 비교하기

score, coef_, intercept_

In [10]:
# 숙제 : LinearRegression, Ridge, Lasso, ElasticNet 학습 및 비교 -> score, coef_, intercept_

In [11]:
print(x)
print(y)

        CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93   0.0  0.573  ...  1.0  273.0     21.0  396.90   7.88

[506 rows x 13 columns]
     PRICE
0   

In [22]:
# LinearRegression

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [24]:
model = LinearRegression()

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=1)

In [26]:
model.fit(x_train, y_train)

LinearRegression()

In [27]:
# 모델이 데이터를 얼마나 잘 예측하는지
model.score(x_test, y_test)

0.7789410172622842

In [28]:
# 각 변수가 주택가격에 미치는 영향력
model.coef_

array([[-1.14428903e-01,  5.71299780e-02,  3.83002824e-02,
         2.42854641e+00, -2.12326236e+01,  2.87723416e+00,
         6.91118094e-03, -1.47158266e+00,  3.05784197e-01,
        -1.06750361e-02, -9.96138270e-01,  6.27746234e-03,
        -5.57414427e-01]])

In [29]:
# 모든 변수가 0일때 기본 가격 (y절편)
model.intercept_

array([45.19251539])

In [30]:
# Ridge

In [31]:
from sklearn.linear_model import Ridge

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=1)

In [33]:
# 규제 강도 조절
model = Ridge(alpha=0.5)

In [34]:
model.fit(x_train, y_train)

Ridge(alpha=0.5)

In [35]:
model.score(x_test, y_test)

0.7834962692151985

In [36]:
model.coef_

array([-1.11088561e-01,  5.77695150e-02,  9.13527911e-03,  2.27448929e+00,
       -1.48915693e+01,  2.94144764e+00,  1.57940613e-03, -1.38335060e+00,
        2.93199807e-01, -1.13729101e-02, -9.20654401e-01,  6.65508760e-03,
       -5.64235128e-01])

In [37]:
model.intercept_

array([40.5870558])

In [49]:
# 규제강도 재조절
model = Ridge(alpha=0.8)

In [50]:
model.fit(x_train, y_train)

Ridge(alpha=0.8)

In [51]:
model.score(x_test, y_test)

0.784444612121832

In [52]:
model.coef_

array([-1.09911793e-01,  5.80145831e-02, -1.25368660e-03,  2.21150540e+00,
       -1.26273888e+01,  2.96084704e+00, -2.88884600e-04, -1.35179991e+00,
        2.88870756e-01, -1.16292192e-02, -8.93963853e-01,  6.78938061e-03,
       -5.66930780e-01])

In [53]:
model.intercept_

array([38.97202638])

In [57]:
# Lasso

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [60]:
from sklearn.linear_model import Lasso

In [61]:
model = Lasso(alpha=0.5)

In [62]:
model.fit(x_train, y_train)

Lasso(alpha=0.5)

In [64]:
model.score(x_test, y_test)

0.733129798864913

In [65]:
model.coef_

array([-0.0882369 ,  0.05800307, -0.01636258,  0.        , -0.        ,
        1.59485829,  0.00668738, -0.86844824,  0.26752545, -0.01377449,
       -0.75401407,  0.00690801, -0.68798193])

In [66]:
model.intercept_

array([38.47064333])

In [68]:
# ElasticNet
# Ridge와 Lasso를 절반씩 섞은 회귀 모델

In [69]:
# 데이터 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [70]:
from sklearn.linear_model import ElasticNet

In [71]:
model = ElasticNet(alpha=0.5, l1_ratio=0.5)
# l1_ratio에서 0은 Ridge, 1은 Lasso
# 0.5는 각 규제를 반반씩 섞음

In [72]:
model.fit(x_train, y_train)

ElasticNet(alpha=0.5)

In [73]:
model.score(x_test, y_test)

0.7257045648174844

In [74]:
model.coef_

array([-0.09525758,  0.0610823 , -0.03413635,  0.        , -0.        ,
        1.26338054,  0.00949058, -0.91145411,  0.29268169, -0.01442748,
       -0.7800878 ,  0.00679119, -0.70787025])

In [75]:
model.intercept_

array([41.51258195])