In [26]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [27]:
import tensorflow as tf

In [28]:
tf.__version__

'2.20.0'

In [29]:
import numpy as np

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse

In [30]:
# xor
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [31]:
# layer를 순차적으로 연결
model = Sequential()

In [32]:
# input layer
model.add(Dense(12, input_shape=(2, ), activation="relu"))

# hidden layer
# input_shape을 지정하지 않으면, 자동으로 이전 layer의 output을 잡아준다
model.add(Dense(24, activation="relu"))

# output layer
model.add(Dense(1, activation="sigmoid"))
#결과값이 이진분류 0 또는 1로 나옴. 하나임

c:\Users\user\anaconda3\envs\multi02_tensor\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
# SGD : Stochastic Gradient Descent (확률적 경사하강법)
# metrics : evaluate (평가) 시 추가할 항목 -> 추가하지 않으면 loss 값만 나온다
model.compile(loss=mse, optimizer=SGD(), metrics=["acc"])

In [34]:
# epochs : 학습 횟수
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step - acc: 0.7500 - loss: 0.2461
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - acc: 0.7500 - loss: 0.2461
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - acc: 0.7500 - loss: 0.2460
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - acc: 0.7500 - loss: 0.2459
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - acc: 0.7500 - loss: 0.2457
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - acc: 0.7500 - loss: 0.2456
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.7500 - loss: 0.2455
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - acc: 0.7500 - loss: 0.2454
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - acc: 0.7500 - loss: 0.2453
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - acc: 0.7500 - loss: 0.2452
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - acc: 0.7500 - loss: 0.2451
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - acc: 0.7500 - loss: 0.2450
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━

In [35]:
# 평가 -> loss [acc]
model.evaluate(x, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step - acc: 1.0000 - loss: 0.1588


[0.15881991386413574, 1.0]

In [36]:
predict = model.predict(x)
predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step


array([[0.4167005],
       [0.6193219],
       [0.6224079],
       [0.4173113]], dtype=float32)

In [37]:
model.get_weights()

[array([[ 0.5814592 , -0.6232382 ,  0.3988769 , -0.07509744,  0.62081707,
          0.42644817, -0.5442788 ,  0.484589  , -0.6310076 ,  0.39902323,
          0.16353828,  0.11513797],
        [-0.4008419 ,  0.39619675, -0.60974056, -0.6380355 ,  0.53107965,
         -0.46153778,  0.65488505,  0.07766683, -0.5298502 , -0.49315447,
          0.5387319 ,  0.00721536]], dtype=float32),
 array([-1.2281546e-04,  4.7725797e-02, -4.9393344e-05,  0.0000000e+00,
        -2.2142394e-02,  4.9906518e-02,  6.0612394e-05,  1.2569564e-02,
         0.0000000e+00,  7.0380762e-02,  2.1539131e-02,  7.5980701e-05],
       dtype=float32),
 array([[ 0.12707381, -0.3743835 , -0.4067825 ,  0.22469452,  0.20302606,
          0.35314196,  0.05381029, -0.25083926,  0.19434108,  0.2940066 ,
         -0.25001162, -0.32897538, -0.4134669 , -0.36743277, -0.17688076,
         -0.26512626, -0.18501876,  0.12929156, -0.02887657, -0.39844343,
          0.4283566 , -0.375433  , -0.4037788 , -0.00137573],
        [ 0.14176