In [1]:
import pandas as pd
import numpy as np

In [2]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [3]:
x = pd.DataFrame(data, columns=["CRIM", "ZN", "INDUS", "CHAS", "NOX",
                                "RM","AGE", "DIS","RAD", "TAX", "PTRATIO", "B", "LSTAT"])

y = pd.DataFrame(target, columns=["PRICE"])

LinearRegression, Ridge, Lasso, ElasticNet 학습하여 비교하기

score, coef_, intercept_

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

In [6]:
model_list = [LinearRegression(), Ridge(), Lasso(), ElasticNet()]

In [7]:
names = list()
scores = list()
weights = list()
bias = list()

In [8]:
for model in model_list:
    model.fit(x_train, y_train)

    names.append(model.__class__.__name__)
    scores.append(model.score(x_test, y_test))
    weights.append(model.coef_)
    bias.append(model.intercept_)

In [9]:
models = pd.DataFrame(scores, index=names, columns=["score"])
models

score
LinearRegression  0.783630
Ridge             0.789051
Lasso             0.669478
ElasticNet        0.699816

In [10]:
weights[0] = weights[0].flatten()

In [11]:
weights

[array([-9.85424717e-02,  6.07841138e-02,  5.91715401e-02,  2.43955988e+00,
        -2.14699650e+01,  2.79581385e+00,  3.57459778e-03, -1.51627218e+00,
         3.07541745e-01, -1.12800166e-02, -1.00546640e+00,  6.45018446e-03,
        -5.68834539e-01]),
 array([-8.99352520e-02,  6.20345865e-02,  1.21404325e-02,  2.23426149e+00,
        -1.12838152e+01,  2.89618901e+00, -4.81458007e-03, -1.36998976e+00,
         2.83653073e-01, -1.22828776e-02, -8.84229846e-01,  7.09753443e-03,
        -5.80033848e-01]),
 array([-0.05256765,  0.05904289, -0.        ,  0.        , -0.        ,
         0.        ,  0.01964989, -0.5767539 ,  0.23300934, -0.01230686,
        -0.72109227,  0.00600289, -0.79711475]),
 array([-0.06892062,  0.06229229, -0.        ,  0.        , -0.        ,
         0.60621493,  0.01506499, -0.69022698,  0.26553588, -0.01387045,
        -0.71551352,  0.00639852, -0.75468341])]

In [12]:
weight_list = list()

for i in range(len(weights)):
    temp_dict = dict()
    for j in range(len(x.columns)):
        temp_dict[x.columns[j]] = weights[i][j]
    weight_list.append(temp_dict)

weight_df = pd.DataFrame(weight_list, index=names)
weight_df

CRIM        ZN     INDUS      CHAS        NOX        RM  \
LinearRegression -0.098542  0.060784  0.059172  2.439560 -21.469965  2.795814   
Ridge            -0.089935  0.062035  0.012140  2.234261 -11.283815  2.896189   
Lasso            -0.052568  0.059043 -0.000000  0.000000  -0.000000  0.000000   
ElasticNet       -0.068921  0.062292 -0.000000  0.000000  -0.000000  0.606215   

                       AGE       DIS       RAD       TAX   PTRATIO         B  \
LinearRegression  0.003575 -1.516272  0.307542 -0.011280 -1.005466  0.006450   
Ridge            -0.004815 -1.369990  0.283653 -0.012283 -0.884230  0.007098   
Lasso             0.019650 -0.576754  0.233009 -0.012307 -0.721092  0.006003   
ElasticNet        0.015065 -0.690227  0.265536 -0.013870 -0.715514  0.006399   

                     LSTAT  
LinearRegression -0.568835  
Ridge            -0.580034  
Lasso            -0.797115  
ElasticNet       -0.754683

In [13]:
models["bias"] = list(map(lambda x: x[0], bias))
models

score       bias
LinearRegression  0.783630  46.396494
Ridge             0.789051  38.951619
Lasso             0.669478  46.990859
ElasticNet        0.699816  43.504887

In [14]:
models = pd.concat([weight_df, models], axis=1)
models

CRIM        ZN     INDUS      CHAS        NOX        RM  \
LinearRegression -0.098542  0.060784  0.059172  2.439560 -21.469965  2.795814   
Ridge            -0.089935  0.062035  0.012140  2.234261 -11.283815  2.896189   
Lasso            -0.052568  0.059043 -0.000000  0.000000  -0.000000  0.000000   
ElasticNet       -0.068921  0.062292 -0.000000  0.000000  -0.000000  0.606215   

                       AGE       DIS       RAD       TAX   PTRATIO         B  \
LinearRegression  0.003575 -1.516272  0.307542 -0.011280 -1.005466  0.006450   
Ridge            -0.004815 -1.369990  0.283653 -0.012283 -0.884230  0.007098   
Lasso             0.019650 -0.576754  0.233009 -0.012307 -0.721092  0.006003   
ElasticNet        0.015065 -0.690227  0.265536 -0.013870 -0.715514  0.006399   

                     LSTAT     score       bias  
LinearRegression -0.568835  0.783630  46.396494  
Ridge            -0.580034  0.789051  38.951619  
Lasso            -0.797115  0.669478  46.990859  
ElasticNet       -0.754683  0.699816  43.504887